import { describe, expect, it } from "vitest";
import { dialsBridgeSource } from "../../src/index.ts";

type Listener = (event: { source: unknown; origin: string; data: unknown }) => void;

/** A window for the shipped bridge to run against: a parent that records what it is sent. */
const stubWindow = (options: { origin?: string; framed?: boolean; variables?: unknown } = {}) => {
  const posted: Array<{ message: any; targetOrigin: string }> = [];
  const errors: unknown[][] = [];
  const listeners: Listener[] = [];
  const parent = { postMessage: (message: unknown, targetOrigin: string) => posted.push({ message, targetOrigin }) };
  const win: any = {
    location: { origin: options.origin ?? "http://127.0.0.1:5001" },
    addEventListener: (_type: string, listener: Listener) => listeners.push(listener),
    console: { error: (...args: unknown[]) => errors.push(args) },
    ...(options.variables === undefined ? {} : { __hfVariables: options.variables }),
  };
  win.parent = options.framed === false ? win : parent;
  // The shipped file, evaluated as a browser would run it.
  new Function("window", dialsBridgeSource())(win);
  const send = (data: unknown, from: { source?: unknown; origin?: string } = {}) => {
    for (const listener of listeners) listener({ source: from.source ?? parent, origin: from.origin ?? "http://localhost:8787", data });
  };
  return { win, parent, posted, errors, send };
};

describe("the built bridge", () => {
  it("starts with the generated-file comment and defines dials and defaultDials", () => {
    expect(dialsBridgeSource().split("\n")[0]).toMatch(/^\/\* unframed-dials\.js: generated by Unframed and rewritten on every write\. Do not edit it here/);
    const { win } = stubWindow();
    expect(typeof win.unframed.dials).toBe("function");
    expect(win.unframed.defaultDials({ speed: [2, 0, 5], label: "x" })).toEqual({ speed: 2, label: "x" });
    expect(win.unframed.defaultDials("bad")).toBeNull();
  });

  it("applies the values before announcing them, then returns them", () => {
    const { win, posted } = stubWindow();
    const order: string[] = [];
    const handle = win.unframed.dials("Scene", { accent: "#a78bfa", speed: [1, 0.5, 2] }, (values: unknown) => {
      order.push(`apply ${JSON.stringify(values)} with ${posted.length} posted`);
    });
    expect(order).toEqual(['apply {"accent":"#a78bfa","speed":1} with 0 posted']);
    expect(posted).toEqual([
      {
        message: {
          type: "unframed:dials",
          name: "Scene",
          config: { accent: "#a78bfa", speed: [1, 0.5, 2] },
          schema: { accent: { kind: "color", value: "#a78bfa" }, speed: { kind: "range", value: 1, min: 0.5, max: 2 } },
          values: { accent: "#a78bfa", speed: 1 },
        },
        targetOrigin: "http://127.0.0.1:5001",
      },
    ]);
    expect(handle.values).toEqual({ accent: "#a78bfa", speed: 1 });
  });

  it("reads __hfVariables.unframedDials, so a render's first apply already uses the tuned values", () => {
    const { win } = stubWindow({ variables: { unframedDials: { speed: 1.5, accent: 7, gone: true } } });
    let applied: unknown;
    win.unframed.dials("Scene", { accent: "#a78bfa", speed: [1, 0.5, 2] }, (values: unknown) => (applied = values));
    expect(applied).toEqual({ accent: "#a78bfa", speed: 1.5 });
  });

  it("refuses a bad config with a console error and null, and applies nothing", () => {
    const { win, posted, errors } = stubWindow();
    let applied = false;
    expect(win.unframed.dials("Scene", { speed: [1, 2] }, () => (applied = true))).toBeNull();
    expect(errors).toEqual([["[unframed] dials.speed: an array must be [value, min, max] numbers or a list of strings"]]);
    expect(applied).toBe(false);
    expect(posted).toEqual([]);
  });

  it("names a nameless panel Parameters, logs a failing apply, and announces nothing when not framed", () => {
    const framed = stubWindow();
    framed.win.unframed.dials(null, { on: true }, () => {
      throw new Error("boom");
    });
    expect(framed.posted[0]?.message.name).toBe("Parameters");
    expect(framed.errors[0]?.[0]).toBe("[unframed] applying parameters failed");

    const alone = stubWindow({ framed: false });
    const handle = alone.win.unframed.dials("Scene", { on: true }, undefined);
    expect(handle.values).toEqual({ on: true });
    expect(alone.posted).toEqual([]);
  });

  it("accepts a message only from its parent with its own origin or a loopback one", () => {
    const { win, posted, send } = stubWindow();
    const applied: unknown[] = [];
    win.unframed.dials("Scene", { speed: [1, 0, 5] }, (values: unknown) => applied.push(values));
    posted.length = 0;
    send({ type: "unframed:dials:set", values: { speed: 2 } }, { source: {} });
    send({ type: "unframed:dials:set", values: { speed: 3 } }, { origin: "https://evil.example" });
    send({ type: "unframed:dials:set", values: { speed: 3 } }, { origin: "http://localhost.evil.example:80" });
    send({ type: "unframed:dials:hello" }, { origin: "http://10.0.0.2:8787" });
    expect(applied).toHaveLength(1);
    expect(posted).toEqual([]);
    send({ type: "unframed:dials:set", values: { speed: 4 } }, { origin: "http://[::1]:9000" });
    send({ type: "unframed:dials:set", values: { speed: 5 } }, { origin: "http://127.0.0.1:5001" });
    expect(applied.slice(1)).toEqual([{ speed: 4 }, { speed: 5 }]);
  });

  it("answers hello with an announcement addressed to the asker's origin", () => {
    const { win, posted, send } = stubWindow();
    win.unframed.dials("Scene", { speed: [1, 0, 5] }, () => {});
    posted.length = 0;
    send({ type: "unframed:dials:hello" }, { origin: "http://localhost:8787" });
    expect(posted).toEqual([{ message: expect.objectContaining({ type: "unframed:dials", name: "Scene", values: { speed: 1 } }), targetOrigin: "http://localhost:8787" }]);
  });

  it("keeps what a partial set does not name, re-merges against the schema, and the last declaration wins", () => {
    const { win, send } = stubWindow();
    const applied: unknown[] = [];
    win.unframed.dials("Old", { gone: 1 }, () => applied.push("old"));
    win.unframed.dials("Scene", { accent: "#000000", scene: { speed: [1, 0, 5], label: "x" } }, (values: unknown) => applied.push(values));
    send({ type: "unframed:dials:set", values: { scene: { speed: 3 }, extra: 1 } });
    send({ type: "unframed:dials:set", values: { accent: 12 } });
    expect(applied.slice(-2)).toEqual([
      { accent: "#000000", scene: { speed: 3, label: "x" } },
      { accent: "#000000", scene: { speed: 3, label: "x" } },
    ]);
    expect(applied.filter((item) => item === "old")).toHaveLength(1);
  });
});
