/**
 * Model-facing text for the artifact and preview tools (spec 09), verbatim from
 * `assets/prompts/`. A test holds every constant here to its asset, so edit the asset
 * and this file together.
 */

/** `page-write-tool.md`. The full description is this, one space, then `DIALS_CONTRACT`. */
export const PAGE_WRITE_TEXT = "Create a page asset or write a new version of one. `html` is the complete, self-contained HTML document: inline its style and script; reference the project's images and clips by the exact file names canvas_read reports (they sit beside the page, so a plain relative name works); nothing external loads. Files are never overwritten -- every write is a new version the person can undo. Omit shapeId to create a page beside the current selection; pass it to update that page.";

/** `motion-write-tool.md`. The full description is this, the dials contract, then the timeline rule. */
export const MOTION_WRITE_TEXT = "Create a motion asset -- a HyperFrames composition, an HTML video -- or write a new version of one. `html` is a complete HTML document that follows the HyperFrames contract: the root is <div id=\"root\" data-composition-id=\"main\" data-start=\"0\" data-duration=\"SECONDS\" data-width=\"PX\" data-height=\"PX\"> (data-duration is the render length; size #root to those pixels with overflow hidden); every timed element inside it has an id, class=\"clip\", data-start and data-duration in seconds (.clip is position:absolute; inset:0 -- a full-frame box you lay out inside); <video>, <audio> and <img> clips reference the project's files by the exact names canvas_read reports (they sit beside the composition); a <video> gets muted playsinline, and data-has-audio=\"true\" when its sound should be heard; animation is ONE paused GSAP timeline, registered synchronously: window.__timelines = window.__timelines || {}; window.__timelines.main = gsap.timeline({ paused: true }); give tweens explicit positions and prefer fromTo(); load GSAP with <script src=\"gsap.js\"></script> -- it sits beside the composition -- and nothing else external: no CDNs, fonts or remote images. Never call play(), pause() or set currentTime on media; no wall-clock time, no unseeded randomness, no infinite repeats. The HyperFrames runtime is added to the file for you. Files are never overwritten -- every write is a new version the person can undo. Omit shapeId to create a motion beside the current selection; pass it to update that motion. The person renders it to an MP4 from the node.";

/** `dials-contract.md`: appended to both write descriptions. */
export const DIALS_CONTRACT = "A `dials` object on a page or motion in canvas_read is what its parameters are set to RIGHT NOW -- the person turned them by hand, and those values are what they see and what a render uses. They live on the node, not in the file, so the file you read back still holds the defaults. When you build something FROM an artifact -- stitching, combining, copying -- carry its current values into what you make, or the new thing silently comes out as the original rather than as what they tuned. Parameters: you can expose values for the person to turn by hand, and they appear as controls beside the artifact. Call `unframed.dials(\"Scene\", { accent: \"#a78bfa\", speed: [1, 0.5, 2], caption: \"Launch day\" }, (v) => { /* apply v */ })` -- once, at the end of your script, with a callback that applies the values (set a CSS custom property, a text content, a timeline timeScale). The shape of each value decides its control: a hex colour is a colour picker, `[value, min, max]` (optionally a fourth step) a slider, a string a text field, an array of strings a dropdown, a number or true/false itself, a nested object a folder of controls. The callback runs once at startup and again on every change, and the person's settings are what a render uses -- so apply them, never hard-code the value you also declared. Decide first whether a value is part of the animation. One nothing animates -- a colour, a piece of copy, a size -- is applied straight to the DOM in the callback. One the animation is MADE of -- where a move starts or ends, how long it lasts, its ease -- belongs to the animation and must be given to it rather than written to the DOM: a parameter and whatever animates must never write the same CSS property on the same element, or the parameter reads correctly while the artifact sits still and is overwritten the moment it runs. Expose a parameter when the person asks for one, or when a choice is obviously worth tuning (a colour, a duration, a piece of copy). `unframed` is already there; do not add a script tag for it.";

/** `dials-timeline.md`: appended to the motion write description only. */
export const DIALS_TIMELINE = "When a parameter is part of the animation, build the timeline FROM the values: register it synchronously as above, then inside the callback capture `var at = tl.time()`, call `tl.clear()`, add the tweens using the values, and `tl.seek(at)`. The callback runs once at startup, so the first build is synchronous and a render builds the timeline from the saved values before its first frame; every later change rebuilds it in place, and the runtime keeps the same timeline object throughout. For example: `unframed.dials(\"Move\", { fromX: [0, 0, 500], toX: [300, 0, 500], dur: [2, 0.5, 3] }, function (v) { var at = tl.time(); tl.clear(); tl.fromTo(\"#box\", { x: v.fromX }, { x: v.toX, duration: v.dur }, 0); tl.seek(at); })`. Never set a tweened property directly in the callback; a purely static offset on a tweened element can instead go on a plain wrapper the timeline never touches, which is the same rule from the other side. A value that CHANGES across the timeline is not one parameter: expose its start, its end and the duration as separate controls and let the tween carry it between them. Do not try to express a curve as a parameter -- when something needs a third waypoint the motion wants rewriting, not another dial.";

/** `artifact-performance.md`: appended to both write descriptions, after the dials text. */
export const ARTIFACT_PERFORMANCE = "Performance: the canvas shows many artifacts at once, so keep yours cheap. Animate on demand: draw once at startup and again when a parameter changes, rather than every frame, unless the thing is an animation. When you do need a loop, stop it while `document.hidden` is true or while the page is off screen (use an IntersectionObserver on the root element), and never call `getImageData` or read pixels back from a canvas inside the loop. Prefer CSS transitions and transforms to JavaScript that sets styles every frame. Keep canvases at their displayed size times `devicePixelRatio`, not larger.";

/** `artifact-read-tools.md`. */
export const PAGE_READ_TEXT = "Read the current HTML of a page asset, so an edit starts from what is there.";
export const MOTION_READ_TEXT = "Read the current HTML of a motion asset (its HyperFrames composition), so an edit starts from what is there.";

/** `add-parameter-instruction.md`, with its placeholders. */
export const ADD_PARAMETER_TEMPLATE = "Add <wanted> as <a parameter | parameters> on the <kind> \"<title>\". Expose them with a single `unframed.dials` call so they appear in the Parameters column, and make the callback actually apply each value. If any of them is part of the animation rather than just dressing, wire it into the timeline — rebuild the timeline from the values instead of setting an animated property alongside it — and express anything that changes over time as its start, its end and a duration. Keep every parameter it already has, and change nothing else about it.";

/** The write tools' argument descriptions, from the same two files. */
export const PAGE_WRITE_ARGUMENTS: Readonly<Record<"html" | "shapeId" | "title", string>> = {"html":"The whole HTML document.","shapeId":"The page shape to update. Omit to create a new page.","title":"A short name for the page, shown on the canvas."};
export const MOTION_WRITE_ARGUMENTS: Readonly<Record<"html" | "shapeId" | "title", string>> = {"html":"The whole HTML document.","shapeId":"The motion shape to update. Omit to create a new motion.","title":"A short name for the motion, shown on the canvas."};

/** The read tools' one argument, from `artifact-read-tools.md`. */
export const PAGE_READ_SHAPE_ID = "The page shape.";
export const MOTION_READ_SHAPE_ID = "The motion shape.";

/** `preview-tool-descriptions.md`: each preview tool's description and its arguments'. */
export const PREVIEW_TOOL_TEXT: Readonly<Record<string, { readonly description: string; readonly arguments: Readonly<Record<string, string>> }>> = {
  preview_status: { description: "Report whether this agent session's browser tab exists and is automation-capable, including the page or motion it shows, its URL, title, loading state, viewport mode, and measured CSS-pixel size.", arguments: {} },
  preview_open: { description: "Initialize this agent session's browser tab on the page or motion named by shapeId, or reuse the tab when it already exists. A motion opens in its viewer.", arguments: {"shapeId":"The page or motion shape to open."} },
  preview_navigate: { description: "Navigate this agent session's browser tab to another page or motion of this project, named by shapeId. No other destinations exist.", arguments: {"shapeId":"The page or motion shape to show."} },
  preview_resize: { description: "Resize this agent session's browser tab. Use {mode:'fill'}, {mode:'freeform',width:1024,height:768}, or {mode:'preset',preset:'iphone-12-pro',orientation:'portrait'}. This changes CSS layout breakpoints without changing the desktop browser user agent.", arguments: {"mode":"Viewport mode: fill follows the preview panel, freeform uses exact independently resizable dimensions, and preset uses a named device size.","preset":"Named device size. Required only when mode is preset.","width":"Freeform viewport width in CSS pixels. Required only in freeform mode.","height":"Freeform viewport height in CSS pixels. Required only in freeform mode.","orientation":"Orientation for a named device preset. It is not accepted in fill or freeform mode."} },
  preview_set_appearance: { description: "Emulate prefers-color-scheme in this agent session's browser tab. Use {colorScheme:'dark'} or {colorScheme:'light'} to preview the page in that appearance, and {colorScheme:'system'} to clear the override and follow the OS appearance.", arguments: {"colorScheme":"Emulated prefers-color-scheme for the page: light, dark, or system to follow the OS appearance."} },
  preview_snapshot: { description: "Inspect a page before interacting. Returns page state, semantic elements, diagnostics, action history, and a PNG screenshot. Set includeImage=false for text-only output with the same page metadata.", arguments: {"includeImage":"Include the PNG image in the tool response. Defaults to true. Set false for text-only output."} },
  preview_click: { description: "Click exactly one target in this agent session's browser tab. Prefer a Playwright locator; selector accepts legacy CSS; x and y must be supplied together.", arguments: {"locator":"Playwright selector, preferably role/text based, for example role=button[name='Send'] or text=Continue. Use snapshot first to inspect the page.","selector":"Legacy CSS selector such as button[type='submit']. Prefer locator for resilient role/text targeting.","x":"Viewport-relative X coordinate in CSS pixels. Must be paired with y.","y":"Viewport-relative Y coordinate in CSS pixels. Must be paired with x."} },
  preview_type: { description: "Insert literal text into one input in this agent session's browser tab. Prefer a Playwright locator; set clear=true to replace existing text.", arguments: {"text":"Literal text to insert.","locator":"Playwright selector for the input, for example role=textbox[name='Message'] or textarea[placeholder*='Message'].","selector":"Legacy CSS selector for the input. Prefer locator.","clear":"Clear the existing input value before inserting text. Defaults to false."} },
  preview_press: { description: "Press one keyboard key in this agent session's browser tab. Examples: {key:'Enter'}, {key:'Escape'}, or {key:'a',modifiers:['Meta']}.", arguments: {"key":"Keyboard key name such as Enter, Escape, Tab, ArrowDown, Backspace, or a single character.","modifiers":"Modifier keys held while pressing key."} },
  preview_scroll: { description: "Scroll this agent session's browser tab. Positive deltaY scrolls down and positive deltaX scrolls right; a locator/selector targets a container.", arguments: {"deltaX":"Horizontal scroll delta in CSS pixels. Positive scrolls right. Defaults to 0.","deltaY":"Vertical scroll delta in CSS pixels. Positive scrolls down. Defaults to 0.","locator":"Playwright selector for a scrollable container. Omit to scroll the viewport.","selector":"Legacy CSS selector for a scrollable container. Omit to scroll the viewport."} },
  preview_evaluate: { description: "Evaluate JavaScript in this agent session's browser tab. Returns {value} with a serializable result up to 64 KB; the expression may mutate page state.", arguments: {"expression":"JavaScript expression evaluated in the page's main frame, for example document.title or (() => ({href: location.href}))()."} },
  preview_wait_for: { description: "Wait in this agent session's browser tab until all supplied locator, selector, and text conditions match.", arguments: {"locator":"Playwright selector that must match an element, for example role=button[name='Send'].","selector":"Legacy CSS selector that must match an element. Prefer locator.","text":"Case-sensitive substring that must appear in visible document text.","timeoutMs":"Maximum wait in milliseconds. Defaults to 15000; maximum 60000."} },
};
