// node server/dials.test.js  (also runs as part of `npm test`)
//
// Parameters on an artifact: the shorthand the agent writes, the values that survive a
// rewrite, and the bridge that runs inside the composition. The bridge is GENERATED from
// the same functions this file tests, so it is exercised here too -- evaluated against a
// stub window and driven, because a shipped copy that drifted from the tested definition
// is exactly the failure the generation exists to prevent.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {
  normalizeConfig,
  defaultValues,
  mergeValues,
  bridgeSource,
  ensureDialsLibrary,
  dialsLibraryInstalled,
  DIALS_LIBRARY_FILES,
  BRIDGE,
  BRIDGE_TAG,
} from './dials.js';

// ---- the shorthand: a value is read by its shape ----
{
  const { config, schema, error } = normalizeConfig({
    accent: '#a78bfa',
    short: '#fff',
    speed: [1, 0.5, 2],
    stepped: [1, 0, 10, 0.5],
    title: 'Launch day',
    loud: true,
    count: 3,
    mode: ['wipe', 'fade'],
    scene: { tint: '#101010', gap: [8, 0, 40] },
  });
  assert.equal(error, undefined);
  // A colour is the one that could not be inferred by DialKit: its own `isHexColor` only
  // feeds interpolation, so a bare hex would have rendered as a text field.
  assert.deepEqual(config.accent, { type: 'color', default: '#a78bfa' });
  assert.deepEqual(config.short, { type: 'color', default: '#fff' }, 'three digits is a colour too');
  assert.deepEqual(schema.accent, { kind: 'color', value: '#a78bfa' });
  // A range is DialKit's own form and passes through untouched.
  assert.deepEqual(config.speed, [1, 0.5, 2]);
  assert.deepEqual(schema.speed, { kind: 'range', value: 1, min: 0.5, max: 2 });
  assert.deepEqual(schema.stepped, { kind: 'range', value: 1, min: 0, max: 10, step: 0.5 });
  assert.deepEqual(config.title, { type: 'text', default: 'Launch day' });
  assert.equal(config.loud, true);
  assert.equal(config.count, 3);
  assert.deepEqual(config.mode, { type: 'select', options: ['wipe', 'fade'], default: 'wipe' });
  assert.deepEqual(schema.mode, { kind: 'select', value: 'wipe', options: ['wipe', 'fade'] });
  // A folder nests, and its schema nests with it.
  assert.deepEqual(config.scene, { tint: { type: 'color', default: '#101010' }, gap: [8, 0, 40] });
  assert.equal(schema.scene.kind, 'folder');
  assert.deepEqual(schema.scene.of.gap, { kind: 'range', value: 8, min: 0, max: 40 });

  // The values a config starts at, in the shape that round-trips through JSON and
  // through window.__hfVariables.
  assert.deepEqual(defaultValues(schema), {
    accent: '#a78bfa',
    short: '#fff',
    speed: 1,
    stepped: 1,
    title: 'Launch day',
    loud: true,
    count: 3,
    mode: 'wipe',
    scene: { tint: '#101010', gap: 8 },
  });
}

// ---- a typo is a message, not a control that silently does nothing ----
assert.match(normalizeConfig(null).error, /must be an object/);
assert.match(normalizeConfig([1, 2, 3]).error, /must be an object/);
assert.match(normalizeConfig({ x: [1, 2] }).error, /dials\.x: an array must be/);
assert.match(normalizeConfig({ x: [1, 2, 'three'] }).error, /dials\.x/);
assert.match(normalizeConfig({ x: [] }).error, /dials\.x/);
assert.match(normalizeConfig({ x: () => {} }).error, /dials\.x: a parameter must be/);
// The path names the nested key, so a mistake three folders down is findable.
assert.match(normalizeConfig({ a: { b: { c: [1, 2] } } }).error, /dials\.a\.b\.c/);

// ---- values survive the agent rewriting the composition ----
{
  const { schema } = normalizeConfig({ accent: '#a78bfa', speed: [1, 0.5, 2], scene: { gap: [8, 0, 40] } });
  // What was tuned wins; what the new version does not name is forgotten rather than
  // re-applied to nothing; what it added arrives at its default.
  assert.deepEqual(mergeValues(schema, { accent: '#000000', gone: 'ignored', scene: { gap: 12 } }), {
    accent: '#000000',
    speed: 1,
    scene: { gap: 12 },
  });
  assert.deepEqual(mergeValues(schema, null), defaultValues(schema), 'nothing saved: the defaults');
  assert.deepEqual(mergeValues(schema, undefined), defaultValues(schema));
  // A saved value of the wrong TYPE is refused, not coerced: a colour that came back as a
  // number would be applied to a CSS property as garbage.
  assert.equal(mergeValues(schema, { accent: 42 }).accent, '#a78bfa');
  assert.equal(mergeValues(schema, { speed: 'fast' }).speed, 1);
  assert.equal(mergeValues(schema, { speed: 1.75 }).speed, 1.75);
}

// ---- the bridge, evaluated and driven ----
{
  const src = bridgeSource();
  assert.match(src, /Generated by server\/dials\.js/, 'the copy in a project folder says where it came from');
  assert.equal(BRIDGE_TAG, `<script src="${BRIDGE}"></script>`);

  // A stub window, so the shipped file is what runs rather than a paraphrase of it.
  const run = (hfVariables = null) => {
    const posted = [];
    const listeners = {};
    const win = {
      location: { origin: 'http://127.0.0.1:9' },
      addEventListener: (type, fn) => (listeners[type] = fn),
      ...(hfVariables ? { __hfVariables: hfVariables } : {}),
    };
    win.parent = { postMessage: (msg, origin) => posted.push({ msg, origin }) };
    const quiet = { error() {}, log() {}, warn() {} };
    // eslint-disable-next-line no-new-func
    new Function('window', 'console', src)(win, quiet);
    return { win, posted, listeners };
  };

  {
    const { win, posted } = run();
    const seen = [];
    const controller = win.unframed.dials('Scene', { accent: '#a78bfa', speed: [1, 0.5, 2] }, (v) => seen.push(v));
    // Applied BEFORE anything is announced, so the first frame a render captures is
    // already the tuned one rather than the defaults.
    assert.deepEqual(seen[0], { accent: '#a78bfa', speed: 1 });
    assert.equal(posted.length, 1);
    assert.equal(posted[0].msg.type, 'unframed:dials');
    assert.equal(posted[0].msg.name, 'Scene');
    assert.deepEqual(posted[0].msg.values, { accent: '#a78bfa', speed: 1 });
    assert.deepEqual(posted[0].msg.schema.speed, { kind: 'range', value: 1, min: 0.5, max: 2 });
    // DialKit's own shape travels too, so whoever hosts the panel hands it straight to
    // createDialKit instead of rebuilding it from the schema and getting a kind wrong.
    assert.deepEqual(posted[0].msg.config.accent, { type: 'color', default: '#a78bfa' });
    assert.deepEqual(posted[0].msg.config.speed, [1, 0.5, 2]);
    // Announced to its OWN origin: the viewer is same-origin, and the canvas is only ever
    // reached through it.
    assert.equal(posted[0].origin, 'http://127.0.0.1:9');
    controller.set({ accent: '#123456' });
    assert.deepEqual(seen.at(-1), { accent: '#123456', speed: 1 });
  }

  // A render: the engine injects the node's values as window.__hfVariables before any
  // page script runs, so they are what the first apply uses.
  {
    const { win } = run({ unframedDials: { speed: 1.75 } });
    let applied = null;
    win.unframed.dials('Scene', { accent: '#a78bfa', speed: [1, 0.5, 2] }, (v) => (applied = v));
    assert.deepEqual(applied, { accent: '#a78bfa', speed: 1.75 }, 'the saved value, over the default');
  }

  // A message from the viewer applies; one from anywhere else is not ours.
  {
    const { win, listeners } = run();
    let applied = null;
    win.unframed.dials('Scene', { accent: '#a78bfa', speed: [1, 0.5, 2], scene: { gap: [8, 0, 40] } }, (v) => (applied = v));
    listeners.message({ origin: 'http://127.0.0.1:9', data: { type: 'unframed:dials:set', values: { speed: 2 } } });
    assert.deepEqual(applied, { accent: '#a78bfa', speed: 2, scene: { gap: 8 } });
    // A partial update must not reset what it does not name.
    listeners.message({ origin: 'http://127.0.0.1:9', data: { type: 'unframed:dials:set', values: { accent: '#000000' } } });
    assert.deepEqual(applied, { accent: '#000000', speed: 2, scene: { gap: 8 } }, 'speed survived');
    listeners.message({ origin: 'http://127.0.0.1:9', data: { type: 'unframed:dials:set', values: { scene: { gap: 20 } } } });
    assert.deepEqual(applied, { accent: '#000000', speed: 2, scene: { gap: 20 } }, 'and a folder updates in place');
    const before = JSON.stringify(applied);
    listeners.message({ origin: 'http://evil.test', data: { type: 'unframed:dials:set', values: { accent: '#ffffff' } } });
    assert.equal(JSON.stringify(applied), before, 'a message from another origin changes nothing');
    listeners.message({ origin: 'http://127.0.0.1:9', data: { type: 'something:else', values: { accent: '#ffffff' } } });
    assert.equal(JSON.stringify(applied), before, 'and neither does one that is not ours');
  }

  // A bad config is reported and registers nothing, rather than half a panel.
  {
    const { win, posted } = run();
    assert.equal(win.unframed.dials('Scene', { x: [1, 2] }, () => {}), null);
    assert.equal(posted.length, 0);
  }

  // No parent (the composition opened as the top-level page): nothing is posted, and
  // registering still applies its defaults.
  {
    const posted = [];
    const win = { location: { origin: 'http://127.0.0.1:9' }, addEventListener() {} };
    win.parent = win;
    // eslint-disable-next-line no-new-func
    new Function('window', 'console', src)(win, { error() {} });
    let applied = null;
    win.unframed.dials('Scene', { speed: [1, 0.5, 2] }, (v) => (applied = v));
    assert.deepEqual(applied, { speed: 1 });
    assert.equal(posted.length, 0);
  }
}

// ---- DialKit beside an artifact is opt-in, and installing it is idempotent ----
{
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'unframed-dials-'));
  assert.equal(await dialsLibraryInstalled(dir), false, 'not there by default: it is 250KB nothing needs to render');
  const first = await ensureDialsLibrary(dir);
  assert.deepEqual(first.sort(), [...DIALS_LIBRARY_FILES].sort());
  assert.equal(await dialsLibraryInstalled(dir), true);
  assert.deepEqual(await ensureDialsLibrary(dir), [], 'nothing to do the second time');
  for (const file of DIALS_LIBRARY_FILES) {
    assert.ok((await fs.stat(path.join(dir, file))).size > 0, `${file} is real`);
  }
  // A truncated copy (an interrupted install, a dependency bump) is rewritten.
  await fs.writeFile(path.join(dir, 'dialkit.js'), 'stale');
  assert.deepEqual(await ensureDialsLibrary(dir), ['dialkit.js']);
  await fs.rm(dir, { recursive: true, force: true });
}

console.log('dials.test.js: ok');
