/**
 * tldraw's UI icons drawn from Lucide, the set the rest of the app uses. tldraw paints each
 * icon as a mask from a URL it looks up by name, so each mapped name gets a Lucide SVG as a
 * data URL. Names left out (the style panel's fill, dash, size, font and arrowhead swatches,
 * which Lucide has no match for) keep tldraw's own icon.
 */
import {
  AlignCenterHorizontal,
  AlignCenterVertical,
  AlignEndHorizontal,
  AlignEndVertical,
  AlignHorizontalDistributeCenter,
  AlignStartHorizontal,
  AlignStartVertical,
  AlignVerticalDistributeCenter,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowLeft,
  Bold,
  BookOpen,
  BringToFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  ClipboardCheck,
  ClipboardCopy,
  Cloud,
  Code,
  Copy,
  Crop,
  Diamond,
  Dot,
  Download,
  Ellipsis,
  EllipsisVertical,
  Eraser,
  ExternalLink,
  Frame,
  GripVertical,
  Group,
  Hand,
  Heading,
  Heart,
  Hexagon,
  Highlighter,
  Image,
  Info,
  Italic,
  Library,
  Link,
  List,
  Lock,
  LockOpen,
  Menu,
  MessageSquare,
  Minus,
  MousePointer2,
  MoveUpRight,
  Octagon,
  Pencil,
  PencilLine,
  Pentagon,
  Plus,
  Redo2,
  RotateCcw,
  RotateCw,
  Scan,
  SendToBack,
  Share,
  Slash,
  Square,
  SquareCheck,
  SquareX,
  Star,
  StickyNote,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  TextAlignCenter,
  TextAlignEnd,
  TextAlignStart,
  ToggleLeft,
  ToggleRight,
  Trash2,
  Triangle,
  TriangleAlert,
  Type,
  Underline,
  Undo2,
  Ungroup,
  WandSparkles,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";
import { flushSync } from "react-dom";
import { createRoot } from "react-dom/client";
import type { TLUiIconType } from "tldraw";

const LUCIDE: Partial<Record<TLUiIconType, LucideIcon>> = {
  "tool-pointer": MousePointer2,
  "tool-hand": Hand,
  "tool-pencil": Pencil,
  "tool-eraser": Eraser,
  "tool-arrow": MoveUpRight,
  "tool-text": Type,
  "tool-note": StickyNote,
  "tool-media": Image,
  "tool-highlight": Highlighter,
  "tool-laser": WandSparkles,
  "tool-line": Slash,
  "tool-frame": Frame,
  "tool-screenshot": Scan,
  "geo-rectangle": Square,
  "geo-ellipse": Circle,
  "geo-triangle": Triangle,
  "geo-diamond": Diamond,
  "geo-pentagon": Pentagon,
  "geo-hexagon": Hexagon,
  "geo-octagon": Octagon,
  "geo-star": Star,
  "geo-cloud": Cloud,
  "geo-heart": Heart,
  "geo-x-box": SquareX,
  "geo-check-box": SquareCheck,
  "geo-arrow-up": ArrowBigUp,
  "geo-arrow-down": ArrowBigDown,
  "geo-arrow-left": ArrowBigLeft,
  "geo-arrow-right": ArrowBigRight,
  undo: Undo2,
  redo: Redo2,
  trash: Trash2,
  duplicate: Copy,
  "dots-vertical": EllipsisVertical,
  "dots-horizontal": Ellipsis,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "arrow-left": ArrowLeft,
  plus: Plus,
  minus: Minus,
  check: Check,
  "cross-2": X,
  "check-circle": CircleCheck,
  "cross-circle": CircleX,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  lock: Lock,
  unlock: LockOpen,
  group: Group,
  ungroup: Ungroup,
  link: Link,
  "external-link": ExternalLink,
  download: Download,
  "clipboard-copy": ClipboardCopy,
  "clipboard-copied": ClipboardCheck,
  edit: PencilLine,
  crop: Crop,
  "align-left": AlignStartVertical,
  "align-center-horizontal": AlignCenterVertical,
  "align-right": AlignEndVertical,
  "align-top": AlignStartHorizontal,
  "align-center-vertical": AlignCenterHorizontal,
  "align-bottom": AlignEndHorizontal,
  "distribute-horizontal": AlignHorizontalDistributeCenter,
  "distribute-vertical": AlignVerticalDistributeCenter,
  "stretch-horizontal": StretchHorizontal,
  "stretch-vertical": StretchVertical,
  "bring-to-front": BringToFront,
  "send-to-back": SendToBack,
  "rotate-cw": RotateCw,
  "rotate-ccw": RotateCcw,
  "text-align-left": TextAlignStart,
  "text-align-center": TextAlignCenter,
  "text-align-right": TextAlignEnd,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strike: Strikethrough,
  code: Code,
  heading: Heading,
  bulletList: List,
  highlight: Highlighter,
  comment: MessageSquare,
  menu: Menu,
  "help-circle": CircleQuestionMark,
  "question-mark-circle": CircleQuestionMark,
  "info-circle": Info,
  "warning-triangle": TriangleAlert,
  "toggle-on": ToggleRight,
  "toggle-off": ToggleLeft,
  "share-1": Share,
  manual: BookOpen,
  dot: Dot,
  "drag-handle-dots": GripVertical,
};

/** Icons Unframed's own toolbar buttons name, beside tldraw's. */
const UNFRAMED: Readonly<Record<string, LucideIcon>> = { library: Library };

/** Each mapped tldraw icon name and its Lucide SVG as a data URL, rendered once. */
export const lucideIconUrls = (): Record<string, string> => {
  const host = document.createElement("div");
  const root = createRoot(host);
  const entries = [...Object.entries(LUCIDE), ...Object.entries(UNFRAMED)];
  flushSync(() => root.render(entries.map(([name, Icon]) => <Icon key={name} />)));
  const urls = Object.fromEntries(entries.map(([name], index) => [name, `data:image/svg+xml;utf8,${encodeURIComponent(host.children[index]!.outerHTML)}`]));
  root.unmount();
  return urls;
};
